### ISSUE TITLE
Docker permission issues

### ISSUE THREAD

**Issue by julian-urban** [lehner/gpt#125]
The docker commands listed in the README are not working as intended for me. I believe this is due to security updates of jupyter since the last time this was checked. In particular, in order to access the jupyter server through the browser, I need to use the option `--network host`.

Also, it seems that I can't properly disable read-only mode for the notebooks. Using the option `--user root` appears to work, but changes are not saved between sessions. I might just be doing something wrong and I'm unsure whether this is an issue, but in any case it's not obvious to me how the second docker command in the README is supposed to be used to actually retain the data. Any advice on this would be greatly appreciated.

**Comment by lehner** [comment]
Thanks for reaching out.  I will try to give useful advice.  In order to see if there is a general problem, I ran

   docker run --rm -p 8888:8888 -v $(pwd):/notebooks gptdev/notebook

in my home directory.  I then can create a gpt jupyter notebook and can save it in my home directory successfully.
(My home directory is then mounted as /notebooks in the docker image that hosts jupyter.)
So there is at least one case in which the current README still does exactly what it should do.

Are you running the above command or did you refer to a different instruction?

**Comment by aragon999** [comment]
In general this depends on the host system. So before going further it would be interesting which host OS are you using?

But as already stated these are two different issues, I will try to explain the details and hopefully you can figure out a way to solve them.

Regarding the networking, actually the part `-p 8888:8888` should map the port `8888` of the docker container to the port `8888` of the host system. Which seems to fail with, as you apparently cannot open the web page. Putting the docker container in the host network, using `--network host`, will expose all ports on the docker container in the local network, which seems to work for you, but it might be a security risk on its own (probably not in this case). Note that the docker documentation also states, that when using the host network the port mapping is disabled: https://docs.docker.com/network/host/

Regarding the file permissions, the command `-v $(pwd):/notebooks` should mount the current working directory (`pwd`) into the docker container at `/notebooks`. How docker in general works is, that for example the user id owning a file is just taken 1:1 from the host system. If the user in the docker container has a different id, it cannot write the files. The default user of the images [is `gpt`](https://github.com/lehner/gpt/blob/d07bb19aaf37420f6304943f705bedc85e31c659/docker/shell/Dockerfile#L20-L23) with the user and group id 999:
```
docker run --rm -p 8888:8888 -v $(pwd):/notebooks -it --entrypoint=sh gptdev/notebook
$ id 
uid=999(gpt) gid=999(gpt) groups=999(gpt),27(sudo)
```

So make sure that these files are readable for this user (e.g. in Linux it should be easy using file access lists `facl`s): `sudo setfacl -R -m u:999:rwX ...` (do not run this command if you are unsure what you are doing).

When you run the container using the `root` user, you can write on every file, but apparently it seems, that the mounting of the folder did not work, otherwise the files should be stored there. But I would not recommend to run a container as root, as this user can overwrite everything.

**Comment by julian-urban** [comment]
Thanks for your help, this should be enough info for me to figure it out. If it depends on the host system then I guess this wasn't an actual issue, sorry for wasting everyone's time. I'm very new to docker. For reference, I'm currently using kubuntu 22.04.
