### ISSUE TITLE
project_cbit is inefficient and might lead to infinite loops

### ISSUE THREAD

**Issue by daknuett** [lehner/gpt#60]
https://github.com/lehner/gpt/blob/e6115b7481c5cf0a97a9b1ea044ca7849aa27159/tests/qis/qis.py#L34

If the measurement outcome `val` is impossible the loop will never terminate. For small probabilities, the loop might perform arbitrarily bad.

Suggested fix:

- add `determined_probability=-1` or `rng=None` keyword argument in https://github.com/lehner/gpt/blob/e6115b7481c5cf0a97a9b1ea044ca7849aa27159/lib/gpt/qis/state.py#L120.
- use either
  ```
    if(determined_probability != -1): 
        l = determined_probability
    else:
        l = self.rng.uniform_real()
  ```
  or
  ```
     if(rng is None): 
         rng = self.rng.uniform_real
    l = rng()
  ```
- pass an appropriate `rng` or `determined_probability` to `measure` to ensure the desired value is measured (if possible).

**Comment by lehner** [comment]
Hi Daniel,

this was an imperfection that I accepted since this function is only used in the tests which use a deterministic RNG.  So after the test runs successful once, we can exclude the infinite-loop scenario (which also has negligible probability).  I do, however, concede that this should be avoided even in a test.  I have a simpler solution in mind, which I will implement in the next commit.  Thanks for the quick and careful study!

Cheers,

  Christoph

**Comment by lehner** [comment]
See commit 3b5f774fa58880ac3e1bbbf9aaf19fc3ef9c2ade, closing now.
