### ISSUE TITLE
component-wise operations should not be operators

### ISSUE THREAD

**Issue by krox** [lehner/gpt#84]
The operations in `gpt.component` are non-linear functions on individual components of a lattice, but are nonetheless written in the same way as linear operators. I think this leads to some very unexpected behaviour. In particular

* ```python gpt.component.abs * x ``` computes the norm (as in `sqrt(x.real**2 + x.imag**2) + 0j`) separately on each component of `x`. Its a little unusual to write it with a `*`, but otherwise it does the expected thing.
* ```python gpt.component.exp * x``` computes the exponential separately on each component and also separately on the real and the imaginary part (this is inconsistent with the behaviour of `abs`)
* ```python gpt.component.exp * (-x)``` computes `-exp(x)` (and not `exp(-x)` as one would expect)

I would like to propose two changes:
* The operations in `gpt.component` should simply be functions, not operators. I.e. `exp(x)`  instead of  `exp * x`, as the latter suggest this to be a linear operator, which it isn't. This would then also be in line with with the `gpt.matrix` module.
* It should be consistent wether "component wise" means acting on complex numbers or on real and imaginary part separately. (I think acting on complex numbers is more useful, but there might be usecases for both)

If the notation as (non-linear) operators is kept, at least the expression system needs to be made aware of the non-linearity, so that `exp(-x)` is not silently replaced by `-exp(x)`.

just my subjective opinion of course ;)

**Comment by lehner** [comment]
Thanks for posting this.  The non-linearity of most of the functions is indeed an issue and now fixed with commit d0393105c7924fbfee5e7af1f23155e5d6e5349f .  The behavior of gpt.component.exp, however, already is consistent with abs as it acts on the complex number and not separately on the real and imaginary part.  The test core/matrix.py verifies this explicitly against np.exp as well.  Can you run this test in your local setup and verify that it passes?  If it fails for you, we should talk in the next GPT meeting.
